### ISSUE TITLE
Multiseries bar line chart is not available

### ISSUE THREAD

**Issue by anandmedhekar** [predixdesignsystem/px-simple-bar-chart#11]
## Screenshots (_optional, but very helpful_): **Attached herewith screenshot representing multi series bar comparing the multiple X axis values.** There is no feature as such in px-vis which allows me to plot this basic chart. Please let me know if you need more information.
![image](https://cloud.githubusercontent.com/assets/12048080/25468794/cb572640-2b35-11e7-9109-de3e4fa72476.png)

**Comment by randyaskin** [comment]
The px-simple-bar-chart isn't meant for this use case, but I believe @nonmetalhail had started working on a more fully featured px-vis bar chart component. It's not currently a priority in our backlog.

**Comment by nonmetalhail** [comment]
There is a vis bar component. No chart is planned yet. You can create your own using the vis components.

**Comment by nonmetalhail** [comment]
use px-vis-bar-chart for this
